### ISSUE TITLE
research/requirements-tracing

### ISSUE THREAD

**Issue by lbowes** [yar-sac/design-simulation#4]
Consider splitting this issue up among team members.

### Description
The information contained in the [SAC documents provided by ESRA](http://www.soundingrocket.org/sa-cup-documents--forms.html) need to be converted into actionable tickets/todo-items, with the aim of having a list of requirements that can be checked for completion throughout the project. To be 'complete', a requirement should be marked with:

* the name of the team member who completed it
* the date it was completed
* evidence of completion (links to documents, images, lines of code)

### TODO
- [ ] Decide on a place and format to store requirements, Trello?

Extract requirements from the following documents:
- [ ] [Rules and requirements](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sa_cup_irec_rules___requirements_document_20201006_rev_e.pdf)
- [ ] [Payload challenge](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sdl_payload_challenge_rules_and_info_2017_09_14__1_.pdf)
- [ ] [GPS tracking requirements](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sa_cup_irec-gps_tracking_requirement_and_recommendations__rev_b_final_.pdf)
- [ ] [Design, test, evaluation guide](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sa_cup_irec-design_test___evaluation_guide_20191118__rev_c_final_.pdf)
- [ ] [Range operating procedures](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sa_cup_irec_range_standard_operating_procedures_20190603__baseline_.pdf)
- [ ] [Schedule](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sa_cup_ims-20200816.pdf)
- [ ] [Fees](http://www.soundingrocket.org/uploads/9/0/6/4/9064598/sac_irec_fee_letter.pdf)
